import bagProduct1 from "./assets/images/products/bags/bag-product-01.jpg";
import bagProduct2 from "./assets/images/products/bags/bag-product-02.jpg";
import bagProduct3 from "./assets/images/products/bags/bag-product-03.webp";
import bagProduct4 from "./assets/images/products/bags/bag-product-04.webp";
import bagProduct5 from "./assets/images/products/bags/bag-product-05.webp";
import manProduct1 from "./assets/images/products/men/man-product-01.jpg";
import manProduct2 from "./assets/images/products/men/man-product-02.jpg";
import manProduct3 from "./assets/images/products/men/man-product-03.jpg";
import manProduct4 from "./assets/images/products/men/man-product-04.jpg";
import manProduct5 from "./assets/images/products/men/man-product-05.png";
import manProduct6 from "./assets/images/products/men/man-product-06.webp";
import manProduct7 from "./assets/images/products/men/man-product-07.jpg";
import manProduct8 from "./assets/images/products/men/man-product-08.jpg";
import manProduct9 from "./assets/images/products/men/man-product-09.jpg";
import shoesProduct1 from "./assets/images/products/shoes/shoes-product-01.webp";
import shoesProduct2 from "./assets/images/products/shoes/shoes-product-02.webp";
import shoesProduct3 from "./assets/images/products/shoes/shoes-product-03.webp";
import shoesProduct4 from "./assets/images/products/shoes/shoes-product-04.webp";
import shoesProduct5 from "./assets/images/products/shoes/shoes-product-05.webp";
import watchProduct1 from "./assets/images/products/watches/watch-product-01.jpg";
import watchProduct2 from "./assets/images/products/watches/watch-product-02.jpg";
import watchProduct3 from "./assets/images/products/watches/watch-product-03.webp";
import watchProduct4 from "./assets/images/products/watches/watch-product-04.webp";
import watchProduct5 from "./assets/images/products/watches/watch-product-05.webp";
import watchProduct6 from "./assets/images/products/watches/watch-product-06.webp";
import womanProduct1 from "./assets/images/products/women/woman-product-01.jpg";
import womanProduct2 from "./assets/images/products/women/woman-product-02.jpg";
import womanProduct3 from "./assets/images/products/women/woman-product-03.jpg";
import womanProduct4 from "./assets/images/products/women/woman-product-04.jpg";
import womanProduct5 from "./assets/images/products/women/woman-product-05.jpg";
import womanProduct6 from "./assets/images/products/women/woman-product-06.jpg";
import womanProduct7 from "./assets/images/products/women/woman-product-07.jpg";
import womanProduct8 from "./assets/images/products/women/woman-product-08.jpg";
import womanProduct9 from "./assets/images/products/women/woman-product-09.jpg";
import womanProduct10 from "./assets/images/products/women/woman-product-10.jpg";
import womanProduct11 from "./assets/images/products/women/woman-product-11.jpg";

export const products = [
  {
    id: "bag_product_1",
    name: "Celine Micro Belt Bag",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: bagProduct1,
    price: 70,
    offPrice: 66.5,
    discount: 5,
    type: "bag",
  },
  {
    id: "bag_product_2",
    name: "Black Belt Bag",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: bagProduct2,
    price: 90,
    offPrice: 82.8,
    discount: 8,
    type: "bag",
  },
  {
    id: "bag_product_3",
    name: "Beautiful Chamber Bag",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: bagProduct3,
    price: 135,
    offPrice: 108,
    discount: 20,
    type: "bag",
  },
  {
    id: "bag_product_4",
    name: "Large Duffel Bag",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: bagProduct4,
    price: 110,
    offPrice: 88,
    discount: 20,
    type: "bag",
  },
  {
    id: "bag_product_5",
    name: "Small Duffel Bag ",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: bagProduct5,
    price: 115,
    offPrice: 115,
    discount: 0,
    type: "bag",
  },
  {
    id: "man_product_1",
    name: "Only Check Trouser",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct1,
    price: 110,
    offPrice: 110,
    discount: 0,
    type: "man",
  },
  {
    id: "man_product_2",
    name: "Herschel Supply",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct2,
    price: 95,
    offPrice: 95,
    discount: 0,
    type: "man",
  },
  {
    id: "man_product_3",
    name: "White Comfort T-shirt",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct3,
    price: 165,
    offPrice: 138,
    discount: 16,
    type: "man",
  },
  {
    id: "man_product_4",
    name: "Cool Black T-shirt",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct4,
    price: 140,
    offPrice: 117,
    discount: 16,
    type: "man",
  },
  {
    id: "man_product_5",
    name: "Lee White Pants",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct5,
    price: 80,
    offPrice: 67,
    discount: 16,
    type: "man",
  },
  {
    id: "man_product_6",
    name: "Comedy Shirts",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct6,
    price: 120,
    offPrice: 60,
    discount: 50,
    type: "man",
  },
  {
    id: "man_product_7",
    name: "Regular Fit T-shirt",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct7,
    price: 75,
    offPrice: 37.5,
    discount: 50,
    type: "man",
  },
  {
    id: "man_product_8",
    name: "Stanley Stella Tee Shirt",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct8,
    price: 210,
    offPrice: 105.5,
    discount: 50,
    type: "man",
  },
  {
    id: "man_product_9",
    name: "Classic T-Shirt Mens",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: manProduct9,
    price: 90,
    offPrice: 45,
    discount: 50,
    type: "man",
  },
  {
    id: "shoes_product_1",
    name: "Adidas Black Shoes",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: shoesProduct1,
    price: 95,
    offPrice: 90,
    discount: 0,
    type: "shoes",
  },
  {
    id: "shoes_product_2",
    name: "Adidas Gray Shoes",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: shoesProduct2,
    price: 90,
    offPrice: 90,
    discount: 0,
    type: "shoes",
  },
  {
    id: "shoes_product_3",
    name: "Adidas Pink Shoes",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: shoesProduct3,
    price: 95,
    offPrice: 95,
    discount: 0,
    type: "shoes",
  },
  {
    id: "shoes_product_4",
    name: "Adidas Black Sneakers",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: shoesProduct4,
    price: 120,
    offPrice: 84,
    discount: 30,
    type: "shoes",
  },
  {
    id: "shoes_product_5",
    name: "Adidas Gray Sneakers",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: shoesProduct5,
    price: 100,
    offPrice: 70,
    discount: 30,
    type: "shoes",
  },
  {
    id: "watch_product_1",
    name: "Watch With Jelly Strap ",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: watchProduct1,
    price: 90,
    offPrice: 63,
    discount: 30,
    type: "watch",
  },
  {
    id: "watch_product_2",
    name: "Watch With Fabric Strap ",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: watchProduct2,
    price: 85,
    offPrice: 59.5,
    discount: 30,
    type: "watch",
  },
  {
    id: "watch_product_3",
    name: "Modern Black Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: watchProduct3,
    price: 220,
    offPrice: 220,
    discount: 0,
    type: "watch",
  },
  {
    id: "watch_product_4",
    name: "Beautiful White Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: watchProduct4,
    price: 95,
    offPrice: 95,
    discount: 0,
    type: "watch",
  },
  {
    id: "watch_product_5",
    name: "Modern Brown Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: watchProduct5,
    price: 225,
    offPrice: 225,
    discount: 0,
    type: "watch",
  },
  {
    id: "watch_product_6",
    name: "Beautiful Black Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: watchProduct6,
    price: 205,
    offPrice: 205,
    discount: 0,
    type: "watch",
  },
  {
    id: "woman_product_1",
    name: "Esprit Ruffle Shirt",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct1,
    price: 105,
    offPrice: 63,
    discount: 40,
    type: "women",
  },
  {
    id: "woman_product_2",
    name: "Herschel Supply",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct2,
    price: 120,
    offPrice: 72,
    discount: 40,
    type: "women",
  },
  {
    id: "woman_product_3",
    name: "T-Shirt With Sleeve",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct3,
    price: 85,
    offPrice: 51,
    discount: 40,
    type: "women",
  },
  {
    id: "woman_product_4",
    name: "Classic Trench Coat",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct4,
    price: 90,
    offPrice: 54,
    discount: 40,
    type: "women",
  },
  {
    id: "woman_product_5",
    name: "Front Pocket Jumper",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct5,
    price: 135,
    offPrice: 81,
    discount: 40,
    type: "women",
  },
  {
    id: "woman_product_6",
    name: "Square Neck Back",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct6,
    price: 70,
    offPrice: 70,
    discount: 0,
    type: "women",
  },
  {
    id: "woman_product_7",
    name: "Shirt in Stretch Cotton",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct7,
    price: 220,
    offPrice: 220,
    discount: 0,
    type: "women",
  },
  {
    id: "woman_product_8",
    name: "Pieces Metallic Printed",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct8,
    price: 160,
    offPrice: 160,
    discount: 0,
    type: "women",
  },
  {
    id: "woman_product_9",
    name: "Femme T-Shirt In Stripe",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct9,
    price: 180,
    offPrice: 180,
    discount: 0,
    type: "women",
  },
  {
    id: "woman_product_10",
    name: "Cloud Jersey Cardigan",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct10,
    price: 145,
    offPrice: 145,
    discount: 0,
    type: "women",
  },
  {
    id: "woman_product_11",
    name: "Women Office Wear",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: womanProduct11,
    price: 200,
    offPrice: 200,
    discount: 0,
    type: "women",
  },
];
